---
title: "bayesAnalysisNB"
author: "Shanaa Modchalingam"
date: '2022-02-26'
output: 
  html_notebook:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    
---

```{r setup, include=FALSE, warning=FALSE}
rm(list = ls())      # clean environment

source("src/helper_funcs.R")
library(data.table)
library(tidyverse)
library(ggbeeswarm)
library(rethinking)
library(brms)

```


```{r}
rot_all <- read_delim("data/bl_corrected/bl_corrected_data.csv", 
                               delim = ",", 
                               col_types = cols(.default = col_double(),
                                                targetangle_deg = col_factor(),
                                                strat_use = col_factor(),
                                                ppt = col_factor(),
                                                exp = col_factor(),
                                                block_num = col_factor(),
                                                reach_type = col_factor()))

# separate the nocursor and training data
rot_nocur <- rot_all %>%
  filter(reach_type == "nocursor")


# make summary
nocur_summary <- rot_nocur %>%
  group_by(exp, ppt, block_num, strat_use) %>%
  summarise(mean_devs = mean(angular_dev), 
            sd = sd(angular_dev), 
            ci = vector_confint(angular_dev),
            n = n(), .groups = "drop")

# 
wo_strat_final_blocks <- nocur_summary %>% 
  filter(strat_use == '0') %>% #only the implicit aftereffects
  filter(block_num == '4') # only comparing block 4 data
```


# Bayesian analysis using rethinking package

Below analysis is done using Richard McElreath's rethinking package.

For the first pass, we will assume the distribution is normal
```{r}
head(wo_strat_final_blocks)
```

Here is how our model would look:
$$
\begin{aligned}
I_i \;&\sim\; Normal(\mu_i, \sigma) \\
\mu_i \;&=\; \alpha_{exp[i]} \\
\alpha_j \;&\sim\; Normal(15, 5) \;\;\;\; for \; j = 1,2,3 \\
\sigma \;&\sim\; Exponential(1)
\end{aligned}

$$

```{r}
wo_strat_final_blocks$exp_id <- as.integer(wo_strat_final_blocks$exp)

# set up the model, and quadratic approximation (bunch of exponential distributions used)
m_imp_b4 <-quap(
  alist(
    mean_devs ~ dnorm(mu,sigma),
    mu <- a[exp_id],
    sigma <- b[exp_id],
    a[exp_id] ~ dnorm(15,5),
    b[exp_id] ~ dexp(1)
    ), data = wo_strat_final_blocks)

labels <- c(paste("b[",1:3,"]:",levels(wo_strat_final_blocks$exp), sep=""), paste("a[",1:3,"]:",levels(wo_strat_final_blocks$exp),sep=""))

# rename for better behaviour with ggplot
m_imp_b4_posterior <-  as_tibble(precis( extract.samples(m_imp_b4),depth=2, pars = "a")) %>%
  select(-histogram) %>%
  rename( p5.5 = '5.5%', p94.5 = '94.5%')
m_imp_b4_posterior$labels <- labels

#plot
ggplot(m_imp_b4_posterior, aes(x = labels, y = mean)) +
  geom_point() +
  geom_linerange(aes(ymin = p5.5, ymax = p94.5))
  
```
```{r}
m_imp_b4_posterior
```

# Using brms

Figure out how sigmas are being modeled (see quap above to see how it should look)
```{r}
brm_params <- brm(bf(mean_devs ~ 0 + exp, sigma ~ 0 + exp),
      data = wo_strat_final_blocks, family = gaussian,
      prior = c(prior(normal(15, 5), class = b)),
      iter = 2000, warmup = 500, chains = 4, cores = 4,
      seed = 5)

print(brm_params)
```


```{r}
plot(brm_params)
```
```{r}
plot(conditional_effects(brm_params), points = TRUE)
```

