#Data for sharing
#This uses the dfs generated by the analysis Notebook (works on Feb 15, )
source("analysisFunctions.R")
library(data.table)
library(tidyverse)
library(ggbeeswarm)


tosave_nocur <- nocur_summary_blocks %>% 
  filter(exp == "stepwiseExp" | exp == "longAbruptExp")


tosave_adaptation_short <- training_summary %>% 
  filter(exp == "stepwiseExp" | exp == "longAbruptExp")


tosave_adaptation_long <- rot_training %>% 
  filter(exp == "stepwiseExp" | exp == "longAbruptExp") %>%
  select(trial_num, trial_num_cont, rotation_angle, targetangle_deg, ppt, exp, angular_dev)
tosave_adaptation_long$trial_num_cont <- tosave_adaptation_long$trial_num_cont - 66 #fix trial nums for plotting
tosave_adaptation_long$trial_num <- tosave_adaptation_long$trial_num - 99


fwrite(tosave_nocur, file = "data/shanaa_AE_summaries.csv")
fwrite(tosave_adaptation_short, file = "data/shanaa_Adapt_short.csv")
fwrite(tosave_adaptation_long, file = "data/shanaa_Adapt_long.csv")