#Data for sharing
#This uses the dfs generated by the analysis Notebook (works on Feb 15, )
source("analysisFunctions.R")
library(data.table)
library(tidyverse)
library(ggbeeswarm)


# tosave_nocur <- nocur_summary_blocks %>% 
#   filter(exp == "stepwiseExp" | exp == "longAbruptExp"| exp == "gradualExp")



# stepwise only

tosave_adaptation_long <- rot_training_t %>% 
  filter(exp == "stepped") %>%
  select(trial_num_cont, rotation_angle, targetangle_deg, ppt, exp, angular_dev)


tosave_nocur_long <- rot_nocur_t %>% 
  filter(exp == "stepped") %>%
  select(trial_num_cont, rotation_angle, targetangle_deg, strat_use, ppt, exp, angular_dev)

fwrite(tosave_nocur_long, file = "data/shanaa_step_nocursor.csv")
fwrite(tosave_adaptation_long, file = "data/shanaa_step_adaptation.csv")